ReadBooksEasy.WebUI/Controllers/PersonalAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReadBooksEasy.Domain.Abstract;
using ReadBooksEasy.Domain.Entities;
using System.Web.Security;
using WebMatrix.WebData;
using ReadBooksEasy.WebUI.Filters;
namespace ReadBooksEasy.WebUI.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PersonalAreaController : Controller
    {
        //
        // GET: /PersonalArea/
        private IBookRepository repo;
        public PersonalAreaController(IBookRepository bookRepository) {
            this.repo = bookRepository; 
        }

        protected class RezultOfBookRequest {
            public List<int> idOfUserBook = new List<int>();
            public List<Book> sequence = new List<Book>();
        }
        /*private IUserBookRepository repoUserBook;
        public PersonalAreaController(IUserBookRepository userbookRepository)
        {
            this.repoUserBook = userbookRepository;
        }*/
        public ActionResult Index(int? Own)
        {
            var IdOfUser = WebSecurity.GetUserId(User.Identity.Name);
            ViewBag.idU = IdOfUser;
            ViewBag.Name = User.Identity.Name;
            ViewBag.Message = "Authorize area.";
            Book book = new Book(){nameOfBook="new"};
            //repo.SaveBook(1,book);
            if (Own == 1)
            {
                var sequence = repo.UserBook.Where(u => u.IdUsers == IdOfUser).Select(b => b.Book).ToList();
                sequence.ForEach(b => b.fileOfBook = null);
                //IList<Book> UsersBook = new List<Book>();
                //UsersBook.Add(repo.Books.FirstOrDefault());
                ViewBag.sequence = sequence;
                return View(sequence);
            }
            else
            {
                var sequence = repo.Books.ToList();
                sequence.ForEach(b => b.fileOfBook = null);
                ViewBag.sequence = sequence;
                return View(sequence);
            }
        }

        public JsonResult IndexJson(int? Own)
        {
            var IdOfUser = WebSecurity.GetUserId(User.Identity.Name);
            ViewBag.idU = IdOfUser;
            ViewBag.Name = User.Identity.Name;
            ViewBag.Message = "Authorize area.";
            Book book = new Book() { nameOfBook = "new" };
            RezultOfBookRequest rez = new RezultOfBookRequest();
            //repo.SaveBook(1,book);
            if (Own == 1)
            {
                var sequence = repo.UserBook.Where(u => u.IdUsers == IdOfUser).Select(b => b.Book).ToList();
                sequence.ForEach(b => b.fileOfBook = null);
                rez.idOfUserBook = null;
                rez.sequence = sequence;
                //IList<Book> UsersBook = new List<Book>();
                //UsersBook.Add(repo.Books.FirstOrDefault());
                return Json(rez, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var sequence= repo.Books.ToList();
                sequence.ForEach(b => b.fileOfBook = null);
                rez.idOfUserBook.AddRange(repo.UserBook.Where(u => u.IdUsers == IdOfUser).Select(b => b.idBooks).ToList());
                rez.sequence = sequence;
                return Json(rez, JsonRequestBehavior.AllowGet);
            }
        }

        public void AddBookToUserPlaylist(int idOfBook)
        {
            var IdOfUser = WebSecurity.GetUserId(User.Identity.Name);
            Book book = new Book() { nameOfBook = "new" };

            repo.AddBookToPlaylistUser(IdOfUser,idOfBook);
        }

        public void RemoveBookFromUserPlaylist(int idOfBook)
        {
            var IdOfUser = WebSecurity.GetUserId(User.Identity.Name);
            Book book = new Book() { nameOfBook = "new" };
            repo.RemoveBookFromPlaylistUser(IdOfUser, idOfBook);
        }
        public ActionResult AddBook() {
            return View();
        }
        [HttpPost]
        public ActionResult AddBook(Book book, HttpPostedFileBase bookFile)
        {
            var IdOfUser = WebSecurity.GetUserId(User.Identity.Name);
            if (bookFile != null) {
                book.fileOfBook = new byte[bookFile.ContentLength];
                bookFile.InputStream.Read(book.fileOfBook,0,bookFile.ContentLength);
                repo.SaveBook(IdOfUser,book);
            }
            return RedirectToAction("Index");
        }

        public ActionResult ShowPdf(string idOfBook) {
            int id = Int32.Parse(idOfBook);
            Book bookFromDb = repo.Books.FirstOrDefault(b => b.idBook==id);
            return File(bookFromDb.fileOfBook, "application/pdf");
        }

    }
}

ReadBooksEasy.WebUI/Views/Shared/BooksPartial.cshtml
@model ReadBooksEasy.Domain.Entities.Book
<style type="text/css">
        DIV.item {
            border-top: 1px dotted gray;
            padding-top: .7em;
            margin-bottom: .7em;

        }

            DIV.item:first-child {
                border-top: none;
                padding-top: 0;
            }

            DIV.item H3 {
                font-size: 1.3em;
                margin: 0 0 .25em 0;
            }

            DIV.item H4 {
                font-size: 1.1em;
                margin: .4em 0 0 0;
            }
</style>
<div class="item">
    <h3>@Model.nameOfBook</h3>
    @Model.genreOfBook
    <h4>@Model.ratingOfBook</h4>
    @using (Html.BeginForm("ShowPdf", "PersonalArea"))
    {
        @Html.Hidden("idOfBook", Model.idBook)           
        <input type="submit" value="Show Book" />         
    }
</div>

ReadBooksEasy.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Read Books Easy", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

ReadBooksEasy.WebUI/Views/Shared/_PersonalArea.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("Read Books Easy", "Index", "PersonalArea")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body" style="height:85%;background-color:#ffffff">
        @RenderSection("featured", required: false)
        @RenderBody()
        </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>